//WINDOWS
//2. Permitir conexiones en el firewall de Windows

Abre el Firewall de Windows.

Permite el puerto de la base de datos:

MySQL: 3306

PostgreSQL: 5432

O con PowerShell:

// PowerShell
New-NetFirewallRule -DisplayName "MySQL" -Direction Inbound -LocalPort 3306 -Protocol TCP -Action Allow
New-NetFirewallRule -DisplayName "Postgresql" -Direction Inbound -LocalPort 5432 -Protocol TCP -Action Allow

// OUTPUT
Name                          : {d1641c85-32ca-4d38-9754-af6eef40349a}
DisplayName                   : Postgresql
Description                   :
DisplayGroup                  :
Group                         :
Enabled                       : True
Profile                       : Any
Platform                      : {}
Direction                     : Inbound
Action                        : Allow
EdgeTraversalPolicy           : Block
LooseSourceMapping            : False
LocalOnlyMapping              : False
Owner                         :
PrimaryStatus                 : OK
Status                        : Se analizó la regla correctamente desde el almacén. (65536)
EnforcementStatus             : NotApplicable
PolicyStoreSource             : PersistentStore
PolicyStoreSourceType         : Local
RemoteDynamicKeywordAddresses : {}
PolicyAppId                   :
PackageFamilyName             :



//LINUX
//3. Conéctate desde Ubuntu

Instala el cliente correspondiente:
sudo apt update 
sudo apt install postgresql-client
psql -h <192.168.34.160> -U <arqerito/or windows-users> -d <module>


//powershell 
 Test-NetConnection localhost -Port 5432
 Get-Service *postgres*
 netstat -ano | findstr mysql/postgresql/mariadb/sql/ect

//telnet
